# Generated by Django 4.1.5 on 2023-05-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("release_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(unique=True)),
                ("name", models.TextField()),
                ("bio", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.SmallIntegerField()),
                ("comments", models.TextField()),
                ("wrote_at", models.DateTimeField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.library"
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("comics", "Comics"),
                            ("braille", "Braille"),
                            ("audio", "Audio"),
                            ("movie", "Movie"),
                            ("french", "French"),
                            ("german", "German"),
                        ],
                        default=None,
                        max_length=128,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.library"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writings",
                to="books.person",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="library",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.library"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="readers",
            field=models.ManyToManyField(
                related_name="readings", through="books.Review", to="books.person"
            ),
        ),
        migrations.AddConstraint(
            model_name="booktag",
            constraint=models.UniqueConstraint(
                fields=("library_id", "book", "name"), name="unique_book_tag_per_book"
            ),
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("library_id", "author", "title"), name="unique_book_per_library"
            ),
        ),
    ]
