# Generated by Django 4.1.3 on 2022-12-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="bio",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
