# Generated by Django 4.1.5 on 2023-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["library", "release_date"], name="book_library_release_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="review_rating_idx"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 0), ("rating__lte", 10)),
                name="valid_rating",
            ),
        ),
    ]
